# Generated by Django 4.2.16 on 2024-11-10 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, max_length=10, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('sale', models.FloatField(blank=True, null=True)),
                ('sponsor_bonus', models.FloatField(blank=True, null=True)),
                ('binary_bonus', models.FloatField(blank=True, null=True)),
                ('left_sales', models.FloatField(blank=True, null=True)),
                ('right_sales', models.FloatField(blank=True, null=True)),
                ('carry_forward', models.FloatField(blank=True, null=True)),
                ('matching_bonus', models.FloatField(blank=True, null=True)),
                ('left_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_relation', to='calculator.member')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='calculator.member')),
                ('right_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_relation', to='calculator.member')),
            ],
        ),
    ]
